routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('gallery', 'GalleryController');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['image', 'thumbnail', 'title', 'status'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = Gallery::paginate(10);
        return view('galleries.index', ['images' => $images]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'required',
            'image.*' => 'image|mimes:jpeg,jpg,png,gif|max:8000'
        ]);

        if ($request->hasFile('image')) {
            $images = $request->file('image');

            $org_img = $thm_img = true;

            if (!File::exists('images/gallery/originals/')) {
                $org_img = File::makeDirectory(public_path('images/gallery/originals/'), 0777, true);
            }
            if (!File::exists('images/gallery/thumbnails/')) {
                $thm_img = File::makeDirectory(public_path('images/gallery/thumbnails'), 0777, true);
            }

            foreach ($images as $key => $image) {

                $gallery = new Gallery;

                $filename = rand(1111, 9999) . time() . '.' . $image->getClientOriginalExtension();

                $org_path = 'images/gallery/originals/' . $filename;
                $thm_path = 'images/gallery/thumbnails/' . $filename;

                $gallery->image = 'images/gallery/originals/' . $filename;
                $gallery->thumbnail = 'images/gallery/thumbnails/' . $filename;
                $gallery->title = $request->title;
                $gallery->status = $request->status;

                if (!$gallery->save()) {
//                    flash('Gallery could not be updated.')->error()->important();
                    return redirect()->back()->withInput()->with(['error' => 'Gallery could not be updated.']);
                }

                if (($org_img && $thm_img) == true) {
                    Image::make($image)->fit(900, 500, function ($constraint) {
                        $constraint->upsize();
                    })->save($org_path);
                    Image::make($image)->fit(270, 160, function ($constraint) {
                        $constraint->upsize();
                    })->save($thm_path);
                }
            }
        }

//        flash('Image uploaded successfully.')->success();
        return redirect()->action('GalleryController@index')->with(['success' => 'Image uploaded successfully.']);;
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function show(Gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Gallery $gallery)
    {
        $image = Gallery::findOrFail($request->id);

        if ($image->status == 1) {
            $image->status = 0;
            $status = 'disabled';
        } else {
            $image->status = 1;
            $status = 'enabled';
        }

        if (!$image->save()) {
//            flash('Image could not be reverted.')->error();
            return redirect()->route('gallery.index')->with(['error' => 'Image could not be reverted.']);
        }

//        flash('Image has been successfully ' . $status)->success();
        return redirect()->route('gallery.index')->with(['success' => 'Image has been successfully ' . $status]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Gallery::findOrFail($id);

        if ($post->delete()) {
            Session::flash('success', 'Image successfully deleted.');
        } else {
            Session::flash('error', 'Image could not be deleted.');
        }

        return redirect()->route('gallery.index');
    }
}

resources/views/galleries/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Image gallery with Laravel 7</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Listing Images</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form method="POST" action="{{ route('gallery.store') }}" enctype="multipart/form-data"
                      class="form-inline">
                    <p><small>Note: Total size of uploading files should not be greater than 8 MB.</small></p>
                    <div class="form-group">
                        <label for="">Image</label>
                        <input type="file" name="image[]" accept="image/png, image/jpeg, image/jpg, image/gif"
                               class="form-control" multiple/>
                        <input type="text" name="title" placeholder="Image description (Optional)"
                               class="form-control"/>
                        <select name="status" class="form-control">
                            <option value="1">Publish</option>
                            <option value="0">Save in draft</option>
                        </select>
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-success" style="margin-bottom: 0px;">Upload</button>
                    </div>
                </form>
                <div class="ln_solid"></div>

                @if(empty($images->count()))
                    <p>No record found.</p>
                @else
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">

                            <thead>
                            <tr>
                                <th>SN</th>
                                <th>Image</th>
                                <th>Status</th>
                                <th>Date/Time Added</th>
                                <th>Operations</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach ($images as $image)
                                <tr>
                                    <td>{{ (($images->currentPage() - 1 ) * $images->perPage() ) + $loop->iteration }}</td>
                                    <td><img class="img-responsive thumbnail_img"
                                             src="{{  asset($image->thumbnail) }}"/></td>
                                    <td>
                                        @if($image->status == 1)
                                            <span class="enable">Active</span>
                                        @else
                                            <span class="disable">Inactive</span>
                                        @endif
                                    </td>
                                    <td>{{ $image->updated_at->format('F d, Y') }}</td>
                                    <td>
                                        <form action="{{ route('gallery.update', $image->id) }}" method="post"
                                              onsubmit="return confirm('Revert process will Enable/Disable the image. Continue?');">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="put"/>
                                            <input type="hidden" name="id" value="{{ $image->id }}"/>
                                            <button type="submit" class="btn btn-sm btn-info action_btn">Revert</button>
                                        </form>
                                        <form action="{{ route('gallery.destroy', $image->id) }}" method="post"
                                              onsubmit="return confirm('Are you sure you want to delete this record?');">
                                            <input type="hidden" name="_method" value="DELETE"/>
                                            {{ csrf_field() }}
                                            <button type="submit" name="Delete"
                                                    class="btn btn-sm btn-danger action_btn">Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if($images->total() != 0)
                            <div>Showing
                                {{ ($images->currentpage()-1) * $images->perpage()+1}} to
                                {{(($images->currentpage()-1) * $images->perpage())+$images->count()}} of
                                {{$images->total()}} records
                            </div>
                            {{ $images->links() }}
                        @else
                            No records found.
                        @endif
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>

</body>
</html>